# Generated by Django 3.0.7 on 2020-07-16 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiFan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(help_text='镜像名', max_length=200, verbose_name='镜像名')),
                ('code', models.CharField(default=0, help_text='容器状态', max_length=20, verbose_name='容器状态')),
                ('container_id', models.CharField(help_text='容器ID', max_length=50, verbose_name='容器ID')),
                ('version_opencv', models.CharField(help_text='opencv的版本', max_length=20, verbose_name='opencv的版本')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'guifan',
                'verbose_name_plural': 'guifan',
            },
        ),
    ]
